In [160]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, exc
from datetime import datetime
import argparse
import re
import psycopg2
import math

In [161]:
 db_url = 'postgresql://postgres:root@localhost:5432/NAS'

In [162]:
df = pd.read_excel('Filled_in_Questionnaire_NAD.xlsx')
df=df[1:]
df.columns= df.iloc[0]
df=df[2:]

In [163]:
df = df.ffill(axis = 0)
df

1,NaN,Frequency (Quarterly / Annual),Accounts (National/ Regional),Approach (Production/Expenditure/Income),Revision (FAE/SAE/PE or FRE/SRE/TRE),"Indicator Name (GDP, GVA, PFCE, GFCE etc.)",Industry,Sub-industry,Institutional Sector,Price (Constant Price/ Current Price),Year (with option to select a particular year or range of years),Remarks,Statement No.#
3,NaN,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,"Agriculture, livestock, forestry and fishing",Crops,-,Current Prices\nConstant Prices,From 2011-12 onwards,NaN,4.1 (Current Prices) and 4.2 (Constant Prices)
4,NaN,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,"Agriculture, livestock, forestry and fishing",Livestock,-,Current Prices\nConstant Prices,From 2011-12 onwards,NaN,4.1 (Current Prices) and 4.2 (Constant Prices)
5,NaN,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,"Agriculture, livestock, forestry and fishing",Forestry and logging,-,Current Prices\nConstant Prices,From 2011-12 onwards,NaN,4.1 (Current Prices) and 4.2 (Constant Prices)
6,NaN,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,"Agriculture, livestock, forestry and fishing",Fishing and aquaculture,-,Current Prices\nConstant Prices,From 2011-12 onwards,NaN,4.1 (Current Prices) and 4.2 (Constant Prices)
7,NaN,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,Mining and quarrying,-,-,Current Prices\nConstant Prices,From 2011-12 onwards,NaN,4.1 (Current Prices) and 4.2 (Constant Prices)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,NaN,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,-,-,Private non-financial corporations,Current Prices\n,From 2011-12 onwards,-,9 (Current Prices)
106,NaN,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,-,-,Public Financial Corporations,Current Prices\n,From 2011-12 onwards,-,9 (Current Prices)
107,NaN,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,-,-,Private financial corporations,Current Prices\n,From 2011-12 onwards,-,9 (Current Prices)
108,NaN,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,-,-,General government,Current Prices\n,From 2011-12 onwards,-,9 (Current Prices)
109,NaN,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,-,-,Household sector,Current Prices\n,From 2011-12 onwards,-,9 (Current Prices)

In [164]:
columns_df = ['Frequency (Quarterly / Annual) ', 'Accounts (National/ Regional) ','Approach (Production/Expenditure/Income)', 'Revision (FAE/SAE/PE or FRE/SRE/TRE)','Indicator Name (GDP, GVA, PFCE, GFCE etc.)','Institutional Sector ','Industry','Sub-industry ']

In [165]:
df2 = df[columns_df]

In [166]:
df2

1,Frequency (Quarterly / Annual),Accounts (National/ Regional),Approach (Production/Expenditure/Income),Revision (FAE/SAE/PE or FRE/SRE/TRE),"Indicator Name (GDP, GVA, PFCE, GFCE etc.)",Institutional Sector,Industry,Sub-industry
3,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,-,"Agriculture, livestock, forestry and fishing",Crops
4,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,-,"Agriculture, livestock, forestry and fishing",Livestock
5,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,-,"Agriculture, livestock, forestry and fishing",Forestry and logging
6,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,-,"Agriculture, livestock, forestry and fishing",Fishing and aquaculture
7,Annual,National,Production,FAE/SAE/PE/FRE/SRE/TRE*,GVA,-,Mining and quarrying,-
...,...,...,...,...,...,...,...,...
105,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,Private non-financial corporations,-,-
106,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,Public Financial Corporations,-,-
107,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,Private financial corporations,-,-
108,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,General government,-,-
109,Annual,National,Expenditure,FRE/SRE/TRE,Consumption of Fixed Capital,Household sector,-,-

In [167]:
# createing speret exel 

for key in df2:
    df3 =  df2[key]
    # df3 = df3.str.capitalize()
    df3 = df3.replace("-" , np.nan)
    # df3 = sperator(df3)
    df3 = df3.drop_duplicates()
    df3 = df3.dropna()

    df3 = df3.reset_index(drop = True)
    
    name = ""
    for character in key:
        if character not in ["(" , ")" , "/" , "#"]:
            name+= character
    print(df3)         
    df3.to_excel(f"Nas_MASTER_EXCEL_SHEETS\{name.split(' ')[0]}.xlsx" , index = False)
    # print(name.split(" ")[0])
    print(f"{key} done")

0    Annual
Name: Frequency (Quarterly / Annual) , dtype: object
Frequency (Quarterly / Annual)  done
0    National
Name: Accounts (National/ Regional) , dtype: object
Accounts (National/ Regional)  done
0     Production
1    Expenditure
Name: Approach (Production/Expenditure/Income), dtype: object
Approach (Production/Expenditure/Income) done
0    FAE/SAE/PE/FRE/SRE/TRE*
1                FRE/SRE/TRE
Name: Revision (FAE/SAE/PE or FRE/SRE/TRE), dtype: object
Revision (FAE/SAE/PE or FRE/SRE/TRE) done
0                                          GVA
1                    TOTAL GVA at basic prices
2                        Net Taxes on Products
3                            Taxes on Products
4                        Subsidies on Products
5                                          GDP
6                                          CFC
7                                          NDP
8                       GCF by Industry of Use
9                                         GFCF
10                                        PFCE
11                                        GFCE
12                                         CIS
13                                   Valuables
14                Export of goods and services
15                Import of goods and services
16    Primary income receivable from ROW (net)
17                                         GNI
18      Other current transfers (net) from ROW
19                                        GNDI
20                                Gross Saving
21                               Gross Savings
22                Consumption of Fixed Capital
Name: Indicator Name (GDP, GVA, PFCE, GFCE etc.), dtype: object
Indicator Name (GDP, GVA, PFCE, GFCE etc.) done
0     Public non-financial corporations
1    Private non-financial corporations
2         Public financial corporations
3        Private financial corporations
4                    General government
5            Households including NPISH
6         Public Financial Corporations
7                      Household sector
Name: Institutional Sector , dtype: object
Institutional Sector  done
0          Agriculture, livestock, forestry and fishing
1                                  Mining and quarrying
2                                         Manufacturing
3     Electricity, Gas, Water supply & Other utility...
4                                          Construction
5     Trade, Hotels, Transport, Communication & Serv...
6                 Trade, repair, Hotels and Restaurants
7     Transport, Storage, Communication & Services r...
8        Financial, Real Estate & Professional Services
9                                    Financial services
10    Real estate, Ownership of dwelling & Professio...
11      Public Administration, Defence & Other Services
12                    Public administration and Defence
13                                       Other services
14                            TOTAL GVA at basic prices
Name: Industry, dtype: object
Industry done
0                                                Crops
1                                            Livestock
2                                 Forestry and logging
3                              Fishing and aquaculture
4                 Food products, beverages and tobacco
5               Textiles, apparel and leather products
6                                       Metal products
7                              Machinery and equipment
8                             Other manufactured goods
9                              Trade & repair services
10                                Hotels & restaurants
11                                            Railways
12                                      Road transport
13                                     Water transport
14                                       Air transport
15                    Services incidental to transport
16                                             Storage
17    Communication & services related to broadcasting
18    Communication & Services related to broadcasting
Name: Sub-industry , dtype: object
Sub-industry  done

In [168]:
# Executing the truncate table account
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."accounts" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'accounts' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'accounts' truncated successfully.

In [169]:
# Insert all Accounts 

accountDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Accounts.xlsx')
accountDf.columns=['Accounts']
serial = range(1, len(accountDf) +1)

accountDf2 = pd.DataFrame({
        'account_code': serial,
        'accounts_name': accountDf['Accounts'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'accounts'

accountDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Accounts table updated')

Accounts table updated

In [170]:
# Executing the truncate table approach
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."approach" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'approach' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'approach' truncated successfully.

In [171]:
# Insert all Approach 

approachDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Approach.xlsx')
approachDf.columns=['Approach']
serial = range(1, len(approachDf) +1)

approachDf2 = pd.DataFrame({
        'approach_code': serial,
        'approach_name': approachDf['Approach'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'approach'

approachDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Approach table updated')

Approach table updated

In [172]:
# Executing the truncate table frequency
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."frequency" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'frequencyMaster' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'frequencyMaster' truncated successfully.

In [173]:
# Insert all Frequency 

frequencDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Frequency.xlsx')
frequencDf.columns=['Frequency']
serial = range(1, len(frequencDf) +1)

frequencDf2 = pd.DataFrame({
        'frequency_code': serial,
        'frequency_type': frequencDf['Frequency'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'frequency'

frequencDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'frequencyMaster updated')

frequencyMaster updated

In [174]:
# Executing the truncate table
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."indicator" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'indicater' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'indicater' truncated successfully.

In [175]:
indicaterDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Indicator.xlsx')

In [176]:
indicaterDf

   Indicator Name (GDP, GVA, PFCE, GFCE etc.)
0                                         GVA
1                   TOTAL GVA at basic prices
2                       Net Taxes on Products
3                           Taxes on Products
4                       Subsidies on Products
5                                         GDP
6                                         CFC
7                                         NDP
8                      GCF by Industry of Use
9                                        GFCF
10                                       PFCE
11                                       GFCE
12                                        CIS
13                                  Valuables
14               Export of goods and services
15               Import of goods and services
16   Primary income receivable from ROW (net)
17                                        GNI
18     Other current transfers (net) from ROW
19                                       GNDI
20                               Gross Saving
21                              Gross Savings
22               Consumption of Fixed Capital

In [177]:
# Insert all indicater 

indicaterDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Indicator.xlsx')
indicaterDf.columns=['Indicator']
serial = range(1, len(indicaterDf) +1)

indicaterDf2 = pd.DataFrame({
        'indicator_code': serial,
        'indicator_fullname': indicaterDf['Indicator'],
        'indicator_shortname': indicaterDf['Indicator'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'indicator'

indicaterDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'indicaterMaster updated')

indicaterMaster updated

In [178]:
# Executing the truncate table
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."price_at" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'price_at' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'price_at' truncated successfully.

In [179]:
# Insert all indicater 

# priceAtDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Indicator.xlsx')
# priceAtDf.columns=['Indicator']
# serial = range(1, len(priceAtDf) +1)

priceAtDf2 = pd.DataFrame([{
        'price_at_code': '1',
        'price_at_name': 'Current Prices',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"},
                          {
        'price_at_code': '2',
        'price_at_name': 'Constant Prices',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"}])


engine = create_engine(db_url)
table_name = 'price_at'


priceAtDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'price_at updated')

price_at updated

In [180]:
revision_df = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Revision.xlsx')
my_list = []

In [181]:
for key in revision_df.values:
    print(key[0])
    my_list = my_list + key[0].replace('*', '').split('/')



my_list = pd.DataFrame(my_list , columns = revision_df.columns)
my_list = my_list.drop_duplicates()

my_list.to_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Revision.xlsx',index=False)

FAE/SAE/PE/FRE/SRE/TRE*
FRE/SRE/TRE

In [182]:
# Executing the truncate table
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."revision" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'revision' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'revision' truncated successfully.

In [183]:
revision_df = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Revision.xlsx')
my_list = []


for key in revision_df.values:
    print(key[0])
    my_list = my_list + key[0].split('/')



my_list = pd.DataFrame(my_list , columns = revision_df.columns)
# my_list = my_list.str.replace('*', '')
my_list = my_list.drop_duplicates()

my_list.to_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Revision.xlsx',index=False)

FAE
SAE
PE
FRE
SRE
TRE

In [184]:
# Insert all Frequency 

revisionDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Revision.xlsx')
revisionDf.columns=['Revision']
serial = range(1, len(revisionDf) + 1 )

revisionDf2 = pd.DataFrame({
        'revision_code': serial,
        'priority': serial,
        'revision_type': revisionDf['Revision'],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

engine = create_engine(db_url)
table_name = 'revision'

revisionDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'revisionMaster updated')

revisionMaster updated

In [185]:
df_storage = df[["Industry","Sub-industry ","Institutional Sector "]]

df_storage

1,Industry,Sub-industry,Institutional Sector
3,"Agriculture, livestock, forestry and fishing",Crops,-
4,"Agriculture, livestock, forestry and fishing",Livestock,-
5,"Agriculture, livestock, forestry and fishing",Forestry and logging,-
6,"Agriculture, livestock, forestry and fishing",Fishing and aquaculture,-
7,Mining and quarrying,-,-
...,...,...,...
105,-,-,Private non-financial corporations
106,-,-,Public Financial Corporations
107,-,-,Private financial corporations
108,-,-,General government
109,-,-,Household sector

In [186]:
data_list = df_storage['Industry'].unique().tolist()
data_list_frame =  []
for data in data_list:
    data_list_frame.append([data , np.nan , np.nan])
data_list_frame = pd.DataFrame(data_list_frame , columns = ["Industry",	"Sub-industry ","Institutional Sector "])
df_storage = pd.concat([df_storage , data_list_frame])

In [187]:
df_storage = df_storage.replace('-' , np.nan)
df_storage.dropna(how='all', inplace=True)
df_storage = df_storage.drop_duplicates()

In [188]:
df_storage = df_storage.sort_values(["Industry",	"Sub-industry ","Institutional Sector "])

In [189]:
df_storage.to_excel(f"Nas_MASTER_EXCEL_SHEETS\Comman.xlsx" , index = False)

In [190]:
# Executing the truncate table
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."industry_specific_code" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'industry_specific_code' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'industry_specific_code' truncated successfully.

In [191]:
def isnullcheck(val):
    if isinstance(val , float):
        return True
    else:
        return False

In [192]:
# Insert all Frequency 

industrySpecificCodeDf = pd.read_excel(r'C:\Users\T6\Nas_MASTER_EXCEL_SHEETS\Comman.xlsx')
serial = range(1, len(industrySpecificCodeDf) +1)

industrySpecificCodeDf2 = pd.DataFrame({
        'id': serial,
        'industry_name': industrySpecificCodeDf['Industry'],
        'subindustry_name': industrySpecificCodeDf['Sub-industry '],
        'institutional_sector_name': industrySpecificCodeDf['Institutional Sector '],
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"})

In [193]:
institutional_sector_code = []
industry_code = []
subindustry_code = []

counter = 1
for val in industrySpecificCodeDf2.values:
    if isinstance(val[1] , float):
        industry_code.append(None)
    else:
        industry_code.append(str(counter))

    
    if isinstance(val[2] , float):
        subindustry_code.append(None)
    else:
        subindustry_code.append(str(counter))

    
    if isinstance(val[3] , float):
        institutional_sector_code.append(None)
    else:
        institutional_sector_code.append(str(counter))

    counter += 1

In [194]:
industrySpecificCodeDf2['industry_code'] = industry_code
industrySpecificCodeDf2['subindustry_code'] = subindustry_code

industrySpecificCodeDf2['institutional_sector_code'] = institutional_sector_code

industrySpecificCodeDf2 = industrySpecificCodeDf2[['id','industry_code' ,'industry_name','subindustry_code','subindustry_name','institutional_sector_code' , 'institutional_sector_name' , 'created_by', 'updated_by', 'status']]

In [195]:
engine = create_engine(db_url)
table_name = 'industry_specific_code'

industrySpecificCodeDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'industry_specific_code updated')

industry_specific_code updated

In [200]:
try:
    d_dbCon = psycopg2.connect(user='postgres', password='root', host='localhost', port='5432', database='NAS')
    curr = d_dbCon.cursor()
    curr.execute('TRUNCATE TABLE  public."quarter" CASCADE')
    d_dbCon.commit()
    curr.close()
    d_dbCon.close()
    print("Table 'quarter' truncated successfully.")

except psycopg2.Error as e:
    print("Error while truncating table:", e)

Table 'quarter' truncated successfully.

In [201]:
quarterDf2 = pd.DataFrame([{
        'quarter_code': '1',
        'quarter_name': 'Q1',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"},{
        'quarter_code': '2',
        'quarter_name': 'Q2',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"},{
        'quarter_code': '3',
        'quarter_name': 'Q3',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"},{
        'quarter_code': '4',
        'quarter_name': 'Q4',
        'created_by': 'System',
        'updated_by': 'System',
        'status': "Active"}])

engine = create_engine(db_url)
table_name = 'quarter'

quarterDf2.to_sql(table_name, engine, if_exists='append', index=False)
print(f'Quarter updated')

Quarter updated